name: DeployLab CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: deploylab
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/deploylab
      DB_USERNAME: root
      DB_PASSWORD: root123
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: deploylab

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Give Maven Wrapper execute permission
        run: chmod +x mvnw

      - name: Run Maven tests
        run: ./mvnw clean test

      - name: Package application
        run: ./mvnw package -DskipTests

      - name: Configure AWS credentials using OIDC
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t deploylab-app:${{ github.sha }} .

      - name: Tag and push image to ECR
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag deploylab-app:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}